"""clean relationship

Revision ID: 7704e32d6fc8
Revises: d06156f2c321
Create Date: 2020-05-18 23:48:00.444857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7704e32d6fc8'
down_revision = 'd06156f2c321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ExpenditureCategory')
    op.add_column('Expenditure', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Expenditure', 'Category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Expenditure', type_='foreignkey')
    op.drop_column('Expenditure', 'category_id')
    op.create_table('ExpenditureCategory',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"ExpenditureCategory_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('expenditure_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['Category.id'], name='ExpenditureCategory_category_id_fkey'),
    sa.ForeignKeyConstraint(['expenditure_id'], ['Expenditure.id'], name='ExpenditureCategory_expenditure_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ExpenditureCategory_pkey')
    )
    # ### end Alembic commands ###
